geth-prysm-001-exe:
  fullnameOverride: geth-prysm-001-exe
  image:
    repository: ethpandaops/geth
    tag: mdehoog-eip4844-7d7c642

  podLabels:
    network: 4844-devnet-5
    testnet: 4844-devnet-5
    ethereum_network: 4844-devnet-5
    ethereum_role: execution
    consensus_client: prysm
    execution_client: geth
    ethereum_instance: geth-prysm-001

  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi

  p2pNodePort:
    enabled: true
    port: 33221

  persistence:
    enabled: true
    size: 50Gi

  extraArgs:
  - --bootnodes="$(tr '\n' ',' < /data/bootnodes.txt)"
  - --networkid="$(cat /data/chainid.txt)"
  - --ws.api="eth,net,engine,web3,txpool"
  - --http.api="eth,net,engine,web3,txpool"
  - --syncmode=full
  - --gcmode archive

  initContainers:
  - name: init-genesis
    image: ethpandaops/geth:mdehoog-eip4844-7d7c642
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        BOOTNODE_URI=https://config.4844-devnet-5.ethpandaops.io/el/bootnodes;
        GENESIS_URI=https://config.4844-devnet-5.ethpandaops.io/el/genesis.json;
        if ! [ -f /data/genesis_init_done ];
        then
          wget -O /data/genesis.json $GENESIS_URI;
          wget -O /data/bootnodes.txt $BOOTNODE_URI;
          apk update && apk add jq;
          cat /data/genesis.json | jq -r '.config.chainId' > /data/chainid.txt;
          geth init --datadir /data /data/genesis.json;
          touch /data/genesis_init_done;
          echo "genesis init done";
        else
          echo "genesis is already initialized";
        fi;
        echo "bootnode init done: $(cat /data/bootnodes.txt)";
    volumeMounts:
      - name: storage
        mountPath: "/data"

geth-prysm-001-con:
  fullnameOverride: geth-prysm-001-con

  image:
    repository: ethpandaops/prysm
    tag: eip4844-8efb57c
    pullPolicy: Always

  mode: "beacon"

  podLabels:
    network: 4844-devnet-5
    testnet: 4844-devnet-5
    ethereum_network: 4844-devnet-5
    ethereum_role: consensus
    consensus_client: prysm
    execution_client: geth
    ethereum_instance: geth-prysm-001

  resources:
    requests:
      cpu: 2000m
      memory: 5Gi
    limits:
      cpu: 3000m
      memory: 7Gi

  p2pNodePort:
    enabled: false
    startsAt: 31004

  persistence:
    enabled: true
    size: 50Gi

  customCommand:
  - sh
  - -ac
  - >
    exec /app/cmd/beacon-chain/beacon-chain
    --accept-terms-of-use=true
    --datadir=/data
    --p2p-host-ip=$(POD_IP)
    --p2p-tcp-port=13000
    --p2p-udp-port=13000
    --rpc-host=0.0.0.0
    --rpc-port=4000
    --jwt-secret=/data/jwt.hex
    --grpc-gateway-host=0.0.0.0
    --grpc-gateway-port=3500
    --monitoring-host=0.0.0.0
    --monitoring-port=8080
    --bootstrap-node="enr:-Iq4QAw-ZQb0IiosZgDDcK5ehLs1XmwT0BWU1E1W3ZnhlAAwAE3I46dgCsCbeB5QUwcpDmpFfveTfKF7-tiIg0KWGjqGAYXoIfe6gmlkgnY0gmlwhKEjXcqJc2VjcDI1NmsxoQN4HpB2GMFY2MzwO9hGFjqRG47OX4hGDliAG-mJNWkEr4N1ZHCCIyk"
    --genesis-state=/data/testnet_spec/genesis.ssz
    --chain-config-file=/data/testnet_spec/config.yaml
    --execution-endpoint=http://geth-prysm-001-exe:8551

  initContainers:
  - name: init-genesis
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command:
      - sh
      - -ace
      - >
        DEPOSIT_CONTRACT_URI=https://config.4844-devnet-5.ethpandaops.io/deposit_contract.txt;
        DEPOSIT_CONTRACT_BLOCK_URI=https://config.4844-devnet-5.ethpandaops.io/cl/deposit_contract_block.txt;
        DEPLOY_BLOCK_URI=https://config.4844-devnet-5.ethpandaops.io/cl/deploy_block.txt;
        GENESIS_CONFIG_URI=https://config.4844-devnet-5.ethpandaops.io/cl/config.yaml;
        GENESIS_SSZ_URI=https://config.4844-devnet-5.ethpandaops.io/cl/genesis.ssz;
        BOOTNODE_URI=https://config.4844-devnet-5.ethpandaops.io/bootstrap_nodes.txt;
        mkdir -p /data/testnet_spec;
        if ! [ -f /data/testnet_spec/genesis.ssz ];
        then
          wget -O /data/testnet_spec/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
          wget -O /data/testnet_spec/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
          wget -O /data/testnet_spec/deploy_block.txt $DEPLOY_BLOCK_URI;
          wget -O /data/testnet_spec/config.yaml $GENESIS_CONFIG_URI;
          wget -O /data/testnet_spec/genesis.ssz $GENESIS_SSZ_URI;
          wget -O /data/testnet_spec/bootstrap_nodes.txt $BOOTNODE_URI;
          echo "genesis init done";
        else
          echo "genesis exists. skipping...";
        fi;
        echo "bootnode init done: $(cat /data/testnet_spec/bootstrap_nodes.txt)";
    volumeMounts:
      - name: storage
        mountPath: "/data"