# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - gakonst

# role: ethpandaops.general.ethereum_node
ethereum_node_el: reth

# role: ethpandaops.general.reth
reth_container_image: "{{ default_ethereum_client_images.reth }}"
reth_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
reth_container_volumes:
  - "{{ reth_datadir }}:/data"
  - "{{ reth_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
reth_container_command_extra_args:
  - --chain=/network-config/genesis.json
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --db.log-level=debug
  #- --trustedSetup=/network-config/trusted_setup.txt
