# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: dencun-devnet-12
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        dencun-devnet-12: https://checkpoint-sync.dencun-devnet-12.ethpandaops.io
    clientArgs:
      networks:
        dencun-devnet-12:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://979f2b3cd14a1ed9e7636cafaf565b14b08b503b372ca0d96e34069ffa5515b0611a2b9e3df01f41a80d3ecf0853eeed0f63e7e67cc70c6067dbb634b5aa10d1@116.203.220.217:30303?discport=30303,enode://3b6879b705ff8a01ccd166ccb0ecddd4a561bacd4be3f1373759404e173363423793f4b76ab0eb261f6fdef1048baa7b6bca800a2ffd921ece42af653d40dca1@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>@ethstats.dencun-devnet-12.ethpandaops.io:443
              - --Xfilter-on-enr-fork-id=true
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://979f2b3cd14a1ed9e7636cafaf565b14b08b503b372ca0d96e34069ffa5515b0611a2b9e3df01f41a80d3ecf0853eeed0f63e7e67cc70c6067dbb634b5aa10d1@116.203.220.217:30303?discport=30303,enode://3b6879b705ff8a01ccd166ccb0ecddd4a561bacd4be3f1373759404e173363423793f4b76ab0eb261f6fdef1048baa7b6bca800a2ffd921ece42af653d40dca1@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none.cfg
              - --EthStats.Enabled=true
              - --EthStats.Name=k8s-teku-geth-001
              - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>
              - --EthStats.Server=wss://ethstats.dencun-devnet-12.ethpandaops.io/api/
              - --log=INFO
              - --TxPool.BlobSupportEnabled=true
              - --TxPool.PersistentBlobStorageEnabled=true
              - --TxPool.ReportMinutes=5
            geth:
              - --http.api=eth,net,web3,debug,admin,txpool
              - --http.vhosts=*
              - --networkid=7011893062
              - --syncmode=full
              - --bootnodes=enode://979f2b3cd14a1ed9e7636cafaf565b14b08b503b372ca0d96e34069ffa5515b0611a2b9e3df01f41a80d3ecf0853eeed0f63e7e67cc70c6067dbb634b5aa10d1@116.203.220.217:30303?discport=30303,enode://3b6879b705ff8a01ccd166ccb0ecddd4a561bacd4be3f1373759404e173363423793f4b76ab0eb261f6fdef1048baa7b6bca800a2ffd921ece42af653d40dca1@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>@ethstats.dencun-devnet-12.ethpandaops.io
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --prune=htc
              - --networkid=7011893062
              - --db.size.limit=100GB
              - --bootnodes=enode://979f2b3cd14a1ed9e7636cafaf565b14b08b503b372ca0d96e34069ffa5515b0611a2b9e3df01f41a80d3ecf0853eeed0f63e7e67cc70c6067dbb634b5aa10d1@116.203.220.217:30303?discport=30303,enode://3b6879b705ff8a01ccd166ccb0ecddd4a561bacd4be3f1373759404e173363423793f4b76ab0eb261f6fdef1048baa7b6bca800a2ffd921ece42af653d40dca1@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.ethstats_secret}>@ethstats.dencun-devnet-12.ethpandaops.io
            ethereumjs:
              - --gethGenesis=/data/network-config/genesis.json
              - --bootnodes=enode://979f2b3cd14a1ed9e7636cafaf565b14b08b503b372ca0d96e34069ffa5515b0611a2b9e3df01f41a80d3ecf0853eeed0f63e7e67cc70c6067dbb634b5aa10d1@116.203.220.217:30303?discport=30303,enode://3b6879b705ff8a01ccd166ccb0ecddd4a561bacd4be3f1373759404e173363423793f4b76ab0eb261f6fdef1048baa7b6bca800a2ffd921ece42af653d40dca1@68.183.214.202:30303?discport=30303,enode://665838f37b50d709e848ce0e191ba89b67a6a89a046d9e9ca1be80547bec34534fabff93312235cca27917674c7037ba8319aae057374d2365696e2a33398ffa@134.209.145.195:30303?discport=30303
              - --sync=full
              - --maxPeers=25
              - --isSingleNode=true
              - --logLevel=debug
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QPtsWZ3khgjCez8MKR9-s-Y2CGmebezPj8jNLxrAhaipY0gYq4aMpblZg0LvfYaYveIomb1oczN675GimAGThD2GAYw0peHqgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk,enr:-LK4QLTxS2XSf0m_QtLdu7wBFw1qpBW4cKKDoTUEgbca0SmtD9sNxK0_OAecEiBjWcL3bRDkrSej8Nv8gTyk6LpR09MEh2F0dG5ldHOIAAAAAAYAAACEZXRoMpBWns9KUFmZRtwAAAAAAAAAgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQIJFIuIA3NxBqWJ2a9e5x_3F528RHhHNPysp8-S1kCVUoN0Y3CCIyiDdWRwgiMo,enr:-MS4QIjnj9KdZF-zjHnbyz7wGkhX4ZA8SwPGrU5tt_FqPD6xZ93JwW0Jc9ADuECxJUSCCDELWGV7AvsyvmDeKnl2Ee4Eh2F0dG5ldHOIAAAAAMAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQJNHd29NoJj5nmhrt1L1RinUeG_Vp575ZznxyrKBjXDUYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-MW4QOCmTRbMhAP6HEAZUmH7RRiBP5B2vXat_w6S66APDbwdQZHqw8WT4qxa7sklbqQHmWBHYDZW22vsTIMLQF8p6ziBqIdhdHRuZXRziAAAAAAAAAAMhGV0aDKQ7Jx11FBDA5n__________4JpZIJ2NIJpcISG0ZHDhHF1aWOCIymJc2VjcDI1NmsxoQPr5X7Nfz1RRG74C98BzYf-yvV4XhmdT8Cuxiu1b2D-oYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QPtsWZ3khgjCez8MKR9-s-Y2CGmebezPj8jNLxrAhaipY0gYq4aMpblZg0LvfYaYveIomb1oczN675GimAGThD2GAYw0peHqgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk,enr:-LK4QLTxS2XSf0m_QtLdu7wBFw1qpBW4cKKDoTUEgbca0SmtD9sNxK0_OAecEiBjWcL3bRDkrSej8Nv8gTyk6LpR09MEh2F0dG5ldHOIAAAAAAYAAACEZXRoMpBWns9KUFmZRtwAAAAAAAAAgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQIJFIuIA3NxBqWJ2a9e5x_3F528RHhHNPysp8-S1kCVUoN0Y3CCIyiDdWRwgiMo,enr:-MS4QIjnj9KdZF-zjHnbyz7wGkhX4ZA8SwPGrU5tt_FqPD6xZ93JwW0Jc9ADuECxJUSCCDELWGV7AvsyvmDeKnl2Ee4Eh2F0dG5ldHOIAAAAAMAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQJNHd29NoJj5nmhrt1L1RinUeG_Vp575ZznxyrKBjXDUYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-MW4QOCmTRbMhAP6HEAZUmH7RRiBP5B2vXat_w6S66APDbwdQZHqw8WT4qxa7sklbqQHmWBHYDZW22vsTIMLQF8p6ziBqIdhdHRuZXRziAAAAAAAAAAMhGV0aDKQ7Jx11FBDA5n__________4JpZIJ2NIJpcISG0ZHDhHF1aWOCIymJc2VjcDI1NmsxoQPr5X7Nfz1RRG74C98BzYf-yvV4XhmdT8Cuxiu1b2D-oYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=ARCHIVE
              - --validators-graffiti=Barnabass-MacBook-ProðŸ¼
              - --logging=debug
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --Xpeer-rate-limit=100000
              - --Xpeer-request-limit=1000
              - --ignore-weak-subjectivity-period-enabled
              - --Xepochs-store-blobs=max # Keep the blobs forever
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --pprofaddr=0.0.0.0
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QPtsWZ3khgjCez8MKR9-s-Y2CGmebezPj8jNLxrAhaipY0gYq4aMpblZg0LvfYaYveIomb1oczN675GimAGThD2GAYw0peHqgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QLTxS2XSf0m_QtLdu7wBFw1qpBW4cKKDoTUEgbca0SmtD9sNxK0_OAecEiBjWcL3bRDkrSej8Nv8gTyk6LpR09MEh2F0dG5ldHOIAAAAAAYAAACEZXRoMpBWns9KUFmZRtwAAAAAAAAAgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQIJFIuIA3NxBqWJ2a9e5x_3F528RHhHNPysp8-S1kCVUoN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-MS4QIjnj9KdZF-zjHnbyz7wGkhX4ZA8SwPGrU5tt_FqPD6xZ93JwW0Jc9ADuECxJUSCCDELWGV7AvsyvmDeKnl2Ee4Eh2F0dG5ldHOIAAAAAMAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQJNHd29NoJj5nmhrt1L1RinUeG_Vp575ZznxyrKBjXDUYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-MW4QOCmTRbMhAP6HEAZUmH7RRiBP5B2vXat_w6S66APDbwdQZHqw8WT4qxa7sklbqQHmWBHYDZW22vsTIMLQF8p6ziBqIdhdHRuZXRziAAAAAAAAAAMhGV0aDKQ7Jx11FBDA5n__________4JpZIJ2NIJpcISG0ZHDhHF1aWOCIymJc2VjcDI1NmsxoQPr5X7Nfz1RRG74C98BzYf-yvV4XhmdT8Cuxiu1b2D-oYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QPtsWZ3khgjCez8MKR9-s-Y2CGmebezPj8jNLxrAhaipY0gYq4aMpblZg0LvfYaYveIomb1oczN675GimAGThD2GAYw0peHqgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk,enr:-LK4QLTxS2XSf0m_QtLdu7wBFw1qpBW4cKKDoTUEgbca0SmtD9sNxK0_OAecEiBjWcL3bRDkrSej8Nv8gTyk6LpR09MEh2F0dG5ldHOIAAAAAAYAAACEZXRoMpBWns9KUFmZRtwAAAAAAAAAgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQIJFIuIA3NxBqWJ2a9e5x_3F528RHhHNPysp8-S1kCVUoN0Y3CCIyiDdWRwgiMo,enr:-MS4QIjnj9KdZF-zjHnbyz7wGkhX4ZA8SwPGrU5tt_FqPD6xZ93JwW0Jc9ADuECxJUSCCDELWGV7AvsyvmDeKnl2Ee4Eh2F0dG5ldHOIAAAAAMAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQJNHd29NoJj5nmhrt1L1RinUeG_Vp575ZznxyrKBjXDUYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-MW4QOCmTRbMhAP6HEAZUmH7RRiBP5B2vXat_w6S66APDbwdQZHqw8WT4qxa7sklbqQHmWBHYDZW22vsTIMLQF8p6ziBqIdhdHRuZXRziAAAAAAAAAAMhGV0aDKQ7Jx11FBDA5n__________4JpZIJ2NIJpcISG0ZHDhHF1aWOCIymJc2VjcDI1NmsxoQPr5X7Nfz1RRG74C98BzYf-yvV4XhmdT8Cuxiu1b2D-oYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA
              - --self-limiter=blob_sidecars_by_range:256/10
              - --debug-level=debug
              - --quic-port=9001
              - --enr-quic-port=9001
              - --slasher
              - --slasher-history-length=256
              - --slasher-max-db-size=16
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --graffiti=Barnabass-MacBook-ProðŸ¼
              - --bootstrap-node=enr:-Iq4QPtsWZ3khgjCez8MKR9-s-Y2CGmebezPj8jNLxrAhaipY0gYq4aMpblZg0LvfYaYveIomb1oczN675GimAGThD2GAYw0peHqgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQPZLBX2rEiQ20AfN2f1SQLfnGMQd_t7Rq0-HNkYA9d4uoN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QLTxS2XSf0m_QtLdu7wBFw1qpBW4cKKDoTUEgbca0SmtD9sNxK0_OAecEiBjWcL3bRDkrSej8Nv8gTyk6LpR09MEh2F0dG5ldHOIAAAAAAYAAACEZXRoMpBWns9KUFmZRtwAAAAAAAAAgmlkgnY0gmlwhHTL3NmJc2VjcDI1NmsxoQIJFIuIA3NxBqWJ2a9e5x_3F528RHhHNPysp8-S1kCVUoN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-MS4QIjnj9KdZF-zjHnbyz7wGkhX4ZA8SwPGrU5tt_FqPD6xZ93JwW0Jc9ADuECxJUSCCDELWGV7AvsyvmDeKnl2Ee4Eh2F0dG5ldHOIAAAAAMAAAACEZXRoMpDsnHXUUEMDmf__________gmlkgnY0gmlwhES31sqJc2VjcDI1NmsxoQJNHd29NoJj5nmhrt1L1RinUeG_Vp575ZznxyrKBjXDUYhzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-MW4QOCmTRbMhAP6HEAZUmH7RRiBP5B2vXat_w6S66APDbwdQZHqw8WT4qxa7sklbqQHmWBHYDZW22vsTIMLQF8p6ziBqIdhdHRuZXRziAAAAAAAAAAMhGV0aDKQ7Jx11FBDA5n__________4JpZIJ2NIJpcISG0ZHDhHF1aWOCIymJc2VjcDI1NmsxoQPr5X7Nfz1RRG74C98BzYf-yvV4XhmdT8Cuxiu1b2D-oYhzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: ethpandaops/geth
      tag: master-cd58897
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: dencun-devnet-12
      testnet: dencun-devnet-12
      ethereum_network: dencun-devnet-12
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.dencun-devnet-12.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.dencun-devnet-12.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.dencun-devnet-12.ethpandaops.io/el/besu.json;
            BOOTNODES_URI=https://config.dencun-devnet-12.ethpandaops.io/el/bootnodes.txt;
            TRUSTED_SETUP_URI=https://config.dencun-devnet-12.ethpandaops.io/trusted_setup.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/bootnodes.txt $BOOTNODES_URI;
              wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethpandaops/geth:master-cd58897
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: ethpandaops/teku
      tag: master-f733b7c
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: dencun-devnet-12
      testnet: dencun-devnet-12
      ethereum_network: dencun-devnet-12
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.dencun-devnet-12.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.dencun-devnet-12.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.dencun-devnet-12.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootnodes.txt;
          TRUSTED_SETUP_URI=https://config.dencun-devnet-12.ethpandaops.io/trusted_setup.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            wget -O /data/network-config/trusted_setup.txt $TRUSTED_SETUP_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootnodes2.txt;
          mv /data/network-config/bootnodes2.txt /data/network-config/bootnodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
