default_ethereum_client_images:
### Consensus layer clients
  lighthouse: sigp/lighthouse:v5.0.0
  lodestar: chainsafe/lodestar:v1.16.0
  nimbus: statusim/nimbus-eth2:multiarch-v24.2.1
  prysm: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.0.0
  prysm_validator: gcr.io/prysmaticlabs/prysm/validator:v5.0.0
  teku: consensys/teku:24.2.0

### Execution layer clients
  besu: hyperledger/besu:24.1.2
  geth: ethereum/client-go:v1.13.13
  erigon: thorax/erigon:v2.58.0
  ethereumjs: ethpandaops/ethereumjs:master
  nethermind: nethermind/nethermind:1.25.4
  reth: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.19

default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.137
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.23.0
  tx_fuzz: ethpandaops/tx-fuzz:latest
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:0.0.50-debian
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: ethpandaops/ethstats:snapshot
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:0.19.0
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:master-latest
  blobber: parithoshj/blobber:1.0.5
  dugtrio: ethpandaops/dugtrio:latest
