default_ethereum_client_images:
### Consensus layer clients
  lighthouse: ethpandaops/lighthouse:unstable-c55608b
  lodestar: ethpandaops/lodestar:unstable-9262064
  nimbus: ethpandaops/nimbus:unstable-f125a5c
  prysm: gcr.io/prysmaticlabs/prysm/beacon-chain:HEAD-929e9d
  prysm_validator: gcr.io/prysmaticlabs/prysm/validator:HEAD-929e9d
  teku: ethpandaops/teku:master-f733b7c

### Execution layer clients
  besu: ethpandaops/besu:main-80c8a8f
  geth: ethpandaops/geth:master-cd58897
  erigon: ethpandaops/erigon:devel-33fc53f
  ethereumjs: ethpandaops/ethereumjs:master-c5054eb
  nethermind: nethermindeth/nethermind:release-1.25.0
  reth: ethpandaops/reth:main-b1d0dc4


default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.137
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.22.0
  tx_fuzz: ethpandaops/tx-fuzz:1.3.2
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:0.0.50-debian
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: ethpandaops/ethstats:snapshot
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:0.18.0
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:master-latest
  blobber: parithoshj/blobber:1.0.5
  dugtrio: ethpandaops/dugtrio:latest
