# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_cl:
  - AgeManning
  - ethdreamer
  - paulhauner
  - pawanjay176
  - michaelsproul
  - potuz
  - nisdas
  - antondlr
  - realbigsean

# role: validator_keys
validator_keys_sync_files:
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/keys/"
    dest: "{{ lighthouse_validator_datadir }}/keys/"
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/secrets/"
    dest: "{{ lighthouse_validator_datadir }}/secrets/"

# role: ethpandaops.general.ethereum_node
ethereum_node_cl: lighthouse

# role: ethpandaops.general.lighthouse
lighthouse_container_image: "{{ default_ethereum_client_images.lighthouse }}"
lighthouse_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_beacon_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_cl_ports_http_beacon | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_beacon_hostname }}"
lighthouse_container_volumes:
  - "{{ lighthouse_datadir }}:/data"
  - "{{ lighthouse_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lighthouse_container_command_extra_args:
  - --testnet-dir=/network-config
  - --boot-nodes={{ ethereum_cl_bootnodes | join(',') }}
  - --debug-level=debug
lighthouse_validator_container_volumes:
  - "{{ lighthouse_validator_datadir }}:/validator-data"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lighthouse_validator_container_command_extra_args:
  - --testnet-dir=/network-config
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
lighthouse_validator_datadir: /data/lighthouse-validator
lighthouse_container_pull: true
