# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/blockscout.yaml.j2

blockscout:
  fullnameOverride: blockscout

  image:
    repository: blockscout/blockscout
    tag: master
    pullPolicy: IfNotPresent
  replicas: 0
  podAnnotations:
    "promtail.io/ignore_pod": "true"
  resources:
    requests:
      cpu: 2000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 6Gi

  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: explorer.dencun-devnet-12.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  config:
    COIN: ETH
    DATABASE_URL: postgres://postgres:postgres@blockscout-postgresql:5432/blockscout?ssl=false
    DISABLE_EXCHANGE_RATES: "true"
    DISABLE_KNOWN_TOKENS: "true"
    SHOW_PRICE_CHART: "false"
    ENABLE_1559_SUPPORT: "true"
    DISABLE_READ_API: "false"
    DISABLE_WRITE_API: "true"
    ENABLE_TXS_STATS: "true"
    ECTO_USE_SSL: "false"
    SHOW_TXS_CHART: "true"
    ETHEREUM_JSONRPC_VARIANT: "geth"
    ETHEREUM_JSONRPC_HTTP_URL: http://geth-teku-001:8545
    ETHEREUM_JSONRPC_WS_URL: ws://geth-teku-001:8546
    ETHEREUM_JSONRPC_TRACE_URL: http://geth-teku-001:8545
    INDEXER_COIN_BALANCES_BATCH_SIZE: "5"
    NETWORK: Ethereum
    SUBNETWORK: dencun-devnet-12
    BLOCK_TRANSFORMER: base
    POOL_SIZE: "15"
    CHAIN_SPEC_PATH: /config-update/chainspec.json
  extraVolumes:
    - name: config-update
      emptyDir: {}

  extraVolumeMounts:
    - name: config-update
      mountPath: "/config-update"

  initContainers:
    - name: init-config
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
      - sh
      - -ace
      - >
        CHAINSPEC=https://config.dencun-devnet-12.ethpandaops.io/el/chainspec.json;
        mkdir -p /config-update;
        wget -O /config-update/chainspec.json $CHAINSPEC;
        echo "got genesis";
      volumeMounts:
        - name: config-update
          mountPath: /config-update

  serviceMonitor:
    enabled: true

  postgresql:
    replicas: 0
    fullnameOverride: blockscout-postgresql
