mev_boost_container_image: flashbots/mev-boost:1.6.4844.dev5

mev_boost_container_env:
  GENESIS_FORK_VERSION: "0x10{{ ethereum_genesis_fork_version_suffix }}"
  SKIP_RELAY_SIGNATURE_CHECK: "1"
  BOOST_LISTEN_ADDR: 0.0.0.0:{{ mev_boost_server_port }}
  RELAYS: http://0xa55c1285d84ba83a5ad26420cd5ad3091e49c55a813eee651cd467db38a8c8e63192f47955e9376f6b42f6d190571cb5@mev-api.{{ network_subdomain }}:9062

ethereum_node_mev_boost_enabled: true
