# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_cl:
  - dapplion
  - wemeetagain
  - tuyennhv
  - g11tech
  - philknows

# role: validator_keys
validator_keys_sync_files:
  - src: inventories/devnet-4/files/validator_keys/{{ inventory_hostname }}/keys/
    dest: "{{ lodestar_validator_datadir }}/keys/"
  - src: inventories/devnet-4/files/validator_keys/{{ inventory_hostname }}/secrets/
    dest: "{{ lodestar_validator_datadir }}/secrets/"

# role: ethpandaops.general.ethereum_node
ethereum_node_cl: lodestar

# role: ethpandaops.general.lodestar
lodestar_container_image: g11tech/lodestar:4844-jan23
lodestar_ports_http_beacon: 4000
lodestar_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_beacon_hostname }}"
  VIRTUAL_PORT: "{{ lodestar_ports_http_beacon }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_beacon_hostname }}"
lodestar_container_volumes:
  - "{{ lodestar_datadir }}:/data"
  - "{{ lodestar_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ ethereum_network_config_dir }}:/network-config:ro"
lodestar_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --genesisStateFile=/network-config/genesis.ssz
  - --logLevel=debug
  - --bootnodes={{ ethereum_cl_bootnode }}
  - --network.connectToDiscv5Bootnodes
lodestar_validator_container_volumes:
  - "{{ lodestar_validator_datadir }}:/validator-data"
  - "{{ ethereum_network_config_dir }}:/network-config:ro"
lodestar_validator_container_command_extra_args:
  - --paramsFile=/network-config/config.yaml
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
lodestar_validator_datadir: /data/lodestar-validator

# role: ethpandaops.general.ethereum_metrics_exporter
ethereum_metrics_exporter_cl_endpoint: http://lodestar:9596
