# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - MarekM25
  - kamilchodola
  - LukaszRozmej
  - marcindsobczak
  - asdacap
  - rubo
  - smartprogrammer93
  - g11tech
  - cbermudez97
  - flcl42

# role: ethpandaops.general.ethereum_node
ethereum_node_el: nethermind

# role: ethpandaops.general.nethermind
nethermind_container_image: "{{ default_ethereum_client_images.nethermind }}"
nethermind_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
nethermind_container_volumes:
  - "{{ nethermind_datadir }}:/data"
  - "{{ nethermind_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
nethermind_container_command_extra_args:
  - --Init.ChainSpecPath=/network-config/chainspec.json
  - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug
  - --JsonRpc.MaxBatchSize=1000
  - --JsonRpc.MaxBatchResponseBodySize=1000000000
  - --Discovery.Bootnodes={{ ethereum_el_bootnode }}
  - --Init.IsMining=false
  - --Pruning.Mode=None
  - --config=none.cfg
  - --EthStats.Enabled=true
  - --EthStats.Name={{ inventory_hostname }}
  - --EthStats.Secret={{ ethstats_secret }}
  - --EthStats.Server=wss://{{ ethstats_url }}/api/
