# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_cl:
  - tbenr
  - ajsutton
  - rolfyone
  - siladu
  - lucassaldanha

# role: validator_keys
validator_keys_sync_files:
  - src: inventories/devnet-4/files/validator_keys/{{ inventory_hostname }}/teku-keys/
    dest: "{{ teku_validator_datadir }}/keys/"
  - src: inventories/devnet-4/files/validator_keys/{{ inventory_hostname }}/teku-secrets/
    dest: "{{ teku_validator_datadir }}/secrets/"

# role: ethpandaops.general.ethereum_node
ethereum_node_cl: teku

# role: ethpandaops.general.teku
teku_container_image: ethpandaops/teku:4844-interop-1-b77016c
teku_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_beacon_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_cl_ports_http_beacon | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_beacon_hostname }}"
teku_container_volumes:
  - "{{ teku_datadir }}:/data"
  - "{{ teku_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ ethereum_network_config_dir }}:/network-config:ro"
teku_container_command_extra_args:
  - --network=/network-config/config.yaml
  - --initial-state=/network-config/genesis.ssz
  - --p2p-discovery-bootnodes={{ ethereum_cl_bootnode }}
  - --p2p-peer-upper-bound=100
  - --data-storage-non-canonical-blocks-enabled=true
  - --data-storage-mode=PRUNE
  - --validators-graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
  - --logging=info
  - --Xee-version=kilnv2
  - --Xlog-include-p2p-warnings-enabled
  - --Xmetrics-block-timing-tracking-enabled
  - --Xprogressive-balances-mode=USED
  - --Xtrusted-setup=/network-config/trusted_setup.txt
teku_validator_container_volumes:
  - "{{ teku_validator_datadir }}:/validator-data"
  - "{{ ethereum_network_config_dir }}:/network-config:ro"
teku_validator_datadir: /data/teku-validator
