- name: Install dependencies
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: passlib

- name: Generate htpasswd files for nginx auth
  community.general.htpasswd:
    path: "{{ item }}"
    name: "{{ gen_basic_auth_nginx_name }}"
    password: "{{ gen_basic_auth_nginx_password }}"
    mode: "0644"
  loop: "{{ gen_basic_auth_nginx_paths }}"

- name: Add CORS config for beacon endpoint
  ansible.builtin.copy:
    dest: "{{ item }}"
    mode: "0644"
    content: "{{ gen_cors_nginx_config }}"
  loop: "{{ gen_cors_nginx_paths }}"
