forkmon:
  fullnameOverride: forkmon

  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: forkmon.4844-devnet-4.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  endpoints:
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-geth-1.srv.4844-devnet-4.ethpandaops.io
    name: prysm-geth-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-geth-2.srv.4844-devnet-4.ethpandaops.io
    name: prysm-geth-2
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-geth-3.srv.4844-devnet-4.ethpandaops.io
    name: prysm-geth-3
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-geth-4.srv.4844-devnet-4.ethpandaops.io
    name: prysm-geth-4
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-besu-1.srv.4844-devnet-4.ethpandaops.io
    name: prysm-besu-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-ethereumjs-1.srv.4844-devnet-4.ethpandaops.io
    name: prysm-ethereumjs-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-nethermind-1.srv.4844-devnet-4.ethpandaops.io
    name: prysm-nethermind-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.prysm-erigon-1.srv.4844-devnet-4.ethpandaops.io
    name: prysm-erigon-1
    kind: "rpc"

  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.srv.4844-devnet-4.ethpandaops.io
    name: lighthouse-geth-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-geth-2.srv.4844-devnet-4.ethpandaops.io
    name: lighthouse-geth-2
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-besu-1.srv.4844-devnet-4.ethpandaops.io
    name: lighthouse-besu-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-ethereumjs-1.srv.4844-devnet-4.ethpandaops.io
    name: lighthouse-ethereumjs-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.srv.4844-devnet-4.ethpandaops.io
    name: lighthouse-nethermind-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lighthouse-erigon-1.srv.4844-devnet-4.ethpandaops.io
    name: lighthouse-erigon-1
    kind: "rpc"

  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-geth-1.srv.4844-devnet-4.ethpandaops.io
    name: lodestar-geth-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-besu-1.srv.4844-devnet-4.ethpandaops.io
    name: lodestar-besu-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-ethereumjs-1.srv.4844-devnet-4.ethpandaops.io
    name: lodestar-ethereumjs-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-nethermind-1.srv.4844-devnet-4.ethpandaops.io
    name: lodestar-nethermind-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.lodestar-erigon-1.srv.4844-devnet-4.ethpandaops.io
    name: lodestar-erigon-1
    kind: "rpc"

  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-geth-1.srv.4844-devnet-4.ethpandaops.io
    name: teku-geth-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-besu-1.srv.4844-devnet-4.ethpandaops.io
    name: teku-besu-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-ethereumjs-1.srv.4844-devnet-4.ethpandaops.io
    name: teku-ethereumjs-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-nethermind-1.srv.4844-devnet-4.ethpandaops.io
    name: teku-nethermind-1
    kind: "rpc"
  - addr: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@rpc.teku-erigon-1.srv.4844-devnet-4.ethpandaops.io
    name: teku-erigon-1
    kind: "rpc"

  thirdparty_endpoints: []

  config: |
    # How often to reload data from the nodes
    reload_interval = "10s"
    # If specified, a http server will serve static content here
    server_address = "0.0.0.0:{{ .Values.httpPort}}"
    # Shown in the document title, if specified
    chain_name="{{ .Values.network }}"
    # Third party providers
    infura_key          = "<INFURA_API_KEY>"
    infura_endpoint     = "https://mainnet.infura.io/v3/"
    alchemy_key         = "<ALCHEMY_API_KEY>"
    alchemy_endpoint    = "https://eth-mainnet.g.alchemy.com/v2/"
    etherscan_key       = "<ETHERSCAN_API_KEY>"
    etherscan_endpoint  = "https://api.etherscan.io/api"
    [Metrics]
    enabled = false
    endpoint = "<INFLUX_ENDPOINT>"
    username = "<INFLUX_USERNAME>"
    database  = "<INFLUX_DB_NAME>"
    password  = "<INFLUX_PASSWORD>"
    # Local or non third party connection require rpc kind
    {{- range .Values.endpoints }}
    [[clients]]
      url = {{ .addr | quote }}
      name = {{ .name | quote }}
      kind = {{ .kind | quote }}
    {{- end }}
    # Third party client configuration doesn't require url
    # Kind can vary between infura, alchemy or etherscan
    # Recommended to enable rate limit for third party services
    {{- range .Values.thirdparty_endpoints }}
    [[clients]]
      name = {{ .name | quote }}
      kind = {{ .kind | quote }}
      rate_limit = {{ .rate_limit }}
    {{- end }}
