# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/powfaucet.yaml.j2

powfaucet:
  fullnameOverride: powfaucet

  image:
    repository: pk910/powfaucet
    tag: v2-stable
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 200m
      memory: 500Mi
    limits:
      cpu: 400m
      memory: 1Gi

  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: faucet.dencun-msf-1.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix
  httpProxyCount: 2

  faucetTitle: "dencun-msf-1 PoW Faucet"
  faucetPrivkey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.faucet_private_key}>"
  faucetRpcUrl: "https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@rpc.bootnode-1.dencun-msf-1.ethpandaops.io"
  faucetExplorerLink: "https://explorer.dencun-msf-1.ethpandaops.io/tx/{txid}"
  faucetTxGasLimit: 100000

  faucetCaptchaEnabled: true
  faucetCaptchaSitekey: "<path:/secrets/services/services.enc.yaml#hcaptcha | jsonPath {.site_key}>"
  faucetCaptchaSecret: "<path:/secrets/services/services.enc.yaml#hcaptcha | jsonPath {.secret_key}>"

  faucetRecurringLimitsAmountWei: 500000000000000000000 # 500 ETH
  faucetPowEnabled: true
  faucetPowRewardPerHash: 1000000000000000000 # 1 ETH
