- import_playbook: ethpandaops.general.bootstrap_server
  tags: [init-server, bootstrap]

- hosts: all
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: robertdebock.fail2ban
      tags: [init-server, fail2ban]
    - role: geerlingguy.docker
      tags: [init-server, docker]
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
        - name: docker-compose
      tags: [init-server, pip]
    - role: ethpandaops.general.docker_cleanup
      tags: [init-server, docker_cleanup]
    - role: ethpandaops.general.docker_network
      tags: [init-server, docker_network]
    - role: nickhammond.logrotate
      tags: [init-server, logrotate]
    - role: ethpandaops.general.node_exporter
      tags: [init-server, node_exporter]
    - role: ethpandaops.general.prometheus
      tags: [init-server, prometheus]

- hosts: bootnode
  become: true
  roles:
    - role: cl_bootnode
      tags: [cl_bootnode]

- hosts: prysm-geth-1 # EL bootnode, needs to inject nodekey
  become: true
  roles:
    - role: geth_nodekey_import
      tags: [ethereum, geth_nodekey_import]


- hosts: ethereum_node
  serial: "{{ batch_count | default('100%') }}"
  become: true
  roles:
    - role: eth_testnet_config
      tags: [ethereum, eth_testnet_config]
    - role: validator_keys
      tags: [ethereum, validator_keys]
    - role: ethpandaops.general.ethereum_node
      tags: [ethereum, ethereum_node]
    - role: ethpandaops.general.ethereum_metrics_exporter
      tags: [ethereum, ethereum_metrics_exporter]
    - role: ethpandaops.general.docker_nginx_proxy
      tags: [docker_nginx_proxy]
    - role: gen_basic_auth_nginx
      tags: [docker_nginx_proxy]
  post_tasks:
  - name: Wait between runs
    tags: [ethereum, ethereum_node]
    ansible.builtin.pause:
      seconds: >-
        {{
          batch_count is defined | ternary(
              (batch_wait_seconds | default(30)),
              0
            )
        }}
