default_ethereum_client_images:
  # Consensus layer clients
  lighthouse: ethpandaops/lighthouse:realbigsean-devnetv5-fa9c263
  lodestar: g11tech/lodestar:blobs-60b3c-1
  nimbus: statusim/nimbus-eth2:amd64-latest # needs update
  prysm: ethpandaops/prysm:eip4844-9c0c3f5
  teku: ethpandaops/teku:4844-interop-297d15c # needs update
  # Execution layer clients
  besu: ethpandaops/besu:eip-4844-interop-17a4928 # needs update
  geth: ethpandaops/geth:mdehoog-eip4844-47cf187
  erigon: ethpandaops/erigon:roberto-bayardo-eip-4844-2d1be62
  ethereumjs: g11tech/ethereumjs:blobs-b6b63
  nethermind: nethermindeth/nethermind@sha256:2f869878f0aeec35b05ba203b1f09082888d1be5e1d3768086b25ec7048813aa # needs update

default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.31
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.20.0
