# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - garyschulte
  - jflo
  - fab-10
  - matkt
  - gezero
  - siladu
  - pinges
  - jframe
  - macfarla

# role: ethpandaops.general.ethereum_node
ethereum_node_el: besu

# role: ethpandaops.general.besu
besu_container_image: "{{ default_ethereum_client_images.besu }}"
besu_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
  JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
besu_container_volumes:
  - "{{ besu_datadir }}:/data"
  - "{{ besu_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
besu_container_command_extra_args:
  - --network=sepolia
  - --bootnodes={{ ethereum_el_bootnodes | join(',')}}
  - --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,ENGINE,TRACE,WEB3
  - --data-storage-format=BONSAI

besu_container_pull: true

besu_container_ports:
  - "127.0.0.1:{{ besu_ports_http_rpc }}:{{ besu_ports_http_rpc }}"
  - "127.0.0.1:{{ besu_ports_engine }}:{{ besu_ports_engine }}"
  - "{{ besu_ports_p2p }}:{{ besu_ports_p2p }}"
  - "{{ besu_ports_p2p }}:{{ besu_ports_p2p }}/udp"
  - "5005:5005"