# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - Giulio2002
  - yperbasis

# role: ethpandaops.general.ethereum_node
ethereum_node_el: erigon

# role: ethpandaops.general.erigon
erigon_container_image: "{{ default_ethereum_client_images.erigon }}"
erigon_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
erigon_container_command_extra_args:
  - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
  - --http.vhosts=*
  - --ws
  - --prune=htc
  - --chain=sepolia
  - --db.size.limit=100GB
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}

erigon_init_custom_network: false
erigon_init_custom_network_genesis_file: "{{ eth_testnet_config_dir }}/genesis.json"
