ethereumjs_container_name: execution

# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - g11tech
  - acolytec3
  - holgerd77
  - jochem-brouwer

# role: ethpandaops.general.ethereum_node
ethereum_node_el: ethereumjs

# role: ethpandaops.general.ethereumjs
ethereumjs_container_image: "{{ default_ethereum_client_images.ethereumjs }}"
ethereumjs_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
ethereumjs_container_volumes:
  - "{{ ethereumjs_datadir }}:/data"
  - "{{ ethereumjs_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
ethereumjs_container_command_extra_args:
  - --network=sepolia
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
  - --maxPeers=75
  - --isSingleNode=true
  - --logLevel=debug
  #- --trustedSetup=/network-config/trusted_setup.txt