geth_container_name: execution

# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - mariusVanDerWijden
  - holiman
  - karalabe
  - g11tech

# role: ethpandaops.general.ethereum_node
ethereum_node_el: geth

# role: ethpandaops.general.geth
geth_container_image: "{{ default_ethereum_client_images.geth }}"
geth_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
geth_container_command_extra_args:
  - --http.api=eth,net,web3,debug,admin
  - --http.vhosts=*
  - --sepolia
  - --bootnodes={{ ethereum_el_bootnodes | join(',') }}
#  - --syncmode=full

geth_init_custom_network: false
geth_init_custom_network_genesis_file: "{{ eth_testnet_config_dir }}/genesis.json"
geth_container_pull: true