# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: ethpandaops/dora
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    hosts:
      - host: dora.dencun-devnet-12.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: dencun-devnet-12
  configPath: "https://config.dencun-devnet-12.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.dencun-devnet-12.ethpandaops.io/api/v1/nodes/validator-ranges"
  proxyCount: 2

  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
  
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"

  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1.dencun-devnet-12.ethpandaops.io
    name: bootnode-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-besu-1.dencun-devnet-12.ethpandaops.io
    name: lighthouse-besu-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-erigon-1.dencun-devnet-12.ethpandaops.io
    name: lighthouse-erigon-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-erigon-1-arm.dencun-devnet-12.ethpandaops.io
    name: lighthouse-erigon-1-arm
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.dencun-devnet-12.ethpandaops.io
    name: lighthouse-geth-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-geth-1-arm.dencun-devnet-12.ethpandaops.io
    name: lighthouse-geth-1-arm
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.dencun-devnet-12.ethpandaops.io
    name: lighthouse-nethermind-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1-arm.dencun-devnet-12.ethpandaops.io
    name: lighthouse-nethermind-1-arm
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-reth-1.dencun-devnet-12.ethpandaops.io
    name: lighthouse-reth-1
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-reth-1-arm.dencun-devnet-12.ethpandaops.io
    name: lighthouse-reth-1-arm
    priority: -1
    archive: true
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-besu-1.dencun-devnet-12.ethpandaops.io
    name: lodestar-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-erigon-1.dencun-devnet-12.ethpandaops.io
    name: lodestar-erigon-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-ethereumjs-1.dencun-devnet-12.ethpandaops.io
    name: lodestar-ethereumjs-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-geth-1.dencun-devnet-12.ethpandaops.io
    name: lodestar-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-nethermind-1.dencun-devnet-12.ethpandaops.io
    name: lodestar-nethermind-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-nethermind-1-arm.dencun-devnet-12.ethpandaops.io
    name: lodestar-nethermind-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lodestar-reth-1.dencun-devnet-12.ethpandaops.io
    name: lodestar-reth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-besu-1.dencun-devnet-12.ethpandaops.io
    name: nimbus-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-erigon-1.dencun-devnet-12.ethpandaops.io
    name: nimbus-erigon-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-erigon-1-arm.dencun-devnet-12.ethpandaops.io
    name: nimbus-erigon-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-geth-1.dencun-devnet-12.ethpandaops.io
    name: nimbus-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-nethermind-1.dencun-devnet-12.ethpandaops.io
    name: nimbus-nethermind-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-nethermind-1-arm.dencun-devnet-12.ethpandaops.io
    name: nimbus-nethermind-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-reth-1.dencun-devnet-12.ethpandaops.io
    name: nimbus-reth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.nimbus-reth-1-arm.dencun-devnet-12.ethpandaops.io
    name: nimbus-reth-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-besu-1.dencun-devnet-12.ethpandaops.io
    name: teku-besu-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-besu-1-arm.dencun-devnet-12.ethpandaops.io
    name: teku-besu-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-erigon-1.dencun-devnet-12.ethpandaops.io
    name: teku-erigon-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-geth-1.dencun-devnet-12.ethpandaops.io
    name: teku-geth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-geth-1-arm.dencun-devnet-12.ethpandaops.io
    name: teku-geth-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-nethermind-1.dencun-devnet-12.ethpandaops.io
    name: teku-nethermind-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-nethermind-1-arm.dencun-devnet-12.ethpandaops.io
    name: teku-nethermind-1-arm
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-reth-1.dencun-devnet-12.ethpandaops.io
    name: teku-reth-1
    priority: -1
  - url: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.teku-reth-1-arm.dencun-devnet-12.ethpandaops.io
    name: teku-reth-1-arm
    priority: -1
