default_ethereum_client_images:
### Consensus layer clients
  lighthouse: sigp/lighthouse:v4.6.0-rc.0
  lodestar: chainsafe/lodestar:v1.14.0-rc.1
  nimbus: statusim/nimbus-eth2:multiarch-v24.1.1
  prysm: gcr.io/prysmaticlabs/prysm/beacon-chain:v4.2.0-rc.1
  prysm_validator: gcr.io/prysmaticlabs/prysm/validator:v4.2.0-rc.1
  teku: consensys/teku:24.1.0

### Execution layer clients
  besu: hyperledger/besu:24.1.0
  geth: ethereum/client-go:v1.13.9
  erigon: thorax/erigon:v2.56.1
  ethereumjs: ethpandaops/ethereumjs:stable-3981bca
  nethermind: nethermind/nethermind:1.25.0
  reth: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.14

default_tooling_images:
  xatu_sentry: ethpandaops/xatu:0.0.137
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.22.0
  tx_fuzz: ethpandaops/tx-fuzz:1.3.2
  forkmon: skylenet/nodemonitor:darkmode
  forky: ethpandaops/forky:0.0.50-debian
  powfaucet: pk910/powfaucet:v2-stable
  ethstats: ethpandaops/ethstats:snapshot
  homepage: ethpandaops/ethereum-testnet-homepage:latest
  checkpointz: ethpandaops/checkpointz:0.18.0
  blockscout: blockscout/blockscout:master
  beacon_metrics_gazer: dapplion/beacon-metrics-gazer:latest
  eth_fauceth: chainflag/eth-faucet:latest
  blobscan: blossomlabs/blobscan:latest
  blobscan_indexer: blossomlabs/blobscan-indexer:latest
  dora: ethpandaops/dora:master-latest
  blobber: parithoshj/blobber:1.0.5
  dugtrio: ethpandaops/dugtrio:latest
