name: Terraform lint
on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-terraform.yaml'
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-terraform.yaml'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Lint
        working-directory: ./terraform
        run: >
          terraform fmt --recursive --check --list=true --diff
