fauceth:
  fullnameOverride: fauceth

  image:
    repository: skylenet/fauceth
    tag: fix_fee_estimation

  ingress:
    enabled: true

    className: ingress-nginx-public

    hosts:
      - host: faucet.4844-devnet-6.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  secretEnv:
    APP_AMOUNT: "32080000000000000000" # 32.08 ETH
    APP_IMAGEURL: "https://i.imgur.com/M0gEdpw.png"
    APP_TITLE: "4844-devnet-6 Faucet"
    APP_CHAINS: "7011893055"
    APP_LOGGING: "VERBOSE"
    APP_ETHKEY: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.faucet_private_key}>"
    HCAPTCHA_SECRET: "<path:/secrets/services/services.enc.yaml#hcaptcha | jsonPath {.secret_key}>"
    HCAPTCHA_SITEKEY: "<path:/secrets/services/services.enc.yaml#hcaptcha | jsonPath {.site_key}>"

  initContainers:
  - name: init-config
    image: bash:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
    volumeMounts:
      - name: config
        mountPath: /config
    command:
    - bash
    - -ace
    - >
      echo '
      [{
        "name": "4844-devnet-6",
        "chain": "4844Eth",
        "icon": "ethereum",
        "rpc": [
          "http://nethermind-lodestar-001:8545"
        ],
        "faucets": [],
        "nativeCurrency": {
          "name": "Ether",
          "symbol": "ETH",
          "decimals": 18
        },
        "infoURL": "https://ethereum.org",
        "shortName": "eth",
        "chainId": 7011893055,
        "networkId": 7011893055,
        "slip44": 60,
        "ens": {
          "registry":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
        }
      }]
      ' > /config/chains.json;
      cat /config/chains.json;